log('Executing recorded actions')
show_cursor()
log('Click at (519,497)')
page.evaluate(f'var d=document.createElement("div");d.style.position="fixed";d.style.left=514+"px";d.style.top=492+"px";d.style.width="10px";d.style.height="10px";d.style.background="red";d.style.borderRadius="50%";d.style.zIndex="999999";document.body.appendChild(d)')
move_mouse(519, 497)
page.mouse.click(519, 497)
wait_timeout(page, 0.3)
log('Waiting 2.0 seconds after actions')
wait_timeout(page, 2.0)
browser.screenshot(page, 'latest_screenshot.png', full_page=False)
with open('done_1778693662_cf39.txt','w') as f: f.write('ok')