log('Executing recorded actions')
log('Scroll and click at full‑page (1090,264)')
page.evaluate('window.scrollTo(0, 0)')
wait_timeout(page, 0.3)
move_mouse(1090, 264)
page.mouse.click(1090, 264)
wait_timeout(page, 0.3)
log('Waiting 5.0 seconds after actions')
wait_timeout(page, 5.0)
browser.screenshot(page, 'latest_screenshot.png', full_page=True)