log('Executing recorded actions')
show_cursor()
log('Click at (1077,263)')
page.evaluate(f'var d=document.createElement("div");d.style.position="fixed";d.style.left=1072+"px";d.style.top=258+"px";d.style.width="10px";d.style.height="10px";d.style.background="red";d.style.borderRadius="50%";d.style.zIndex="999999";document.body.appendChild(d)')
move_mouse(1077, 263)
page.mouse.click(1077, 263)
wait_timeout(page, 0.3)
save_download_info('downloads.json')
browser.screenshot(page, 'latest_screenshot.png', full_page=False)
with open('done_1778695306_579c.txt','w') as f: f.write('ok')