log('Executing recorded actions')
show_cursor()
log('Click at (524,496)')
page.evaluate(f'var d=document.createElement("div");d.style.position="fixed";d.style.left=519+"px";d.style.top=491+"px";d.style.width="10px";d.style.height="10px";d.style.background="red";d.style.borderRadius="50%";d.style.zIndex="999999";document.body.appendChild(d)')
move_mouse(524, 496)
page.mouse.click(524, 496)
wait_timeout(page, 0.3)
browser.screenshot(page, 'latest_screenshot.png', full_page=False)
with open('done_1778693592_b1b7.txt','w') as f: f.write('ok')